config/routes.rb
Poker::Application.routes.draw do
  resources :line_items

  get "game/index"
  resources :rounds

  resources :players

  get '/players/toggleplay/:id' => 'players#toggleplay',:as => 'toggle_player'

  root :to => "game#index"

  

end

app/models/round.rb
class Round < ActiveRecord::Base
	has_many :line_items
	has_many :players , :through => :line_items
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)
    @round.call_value = @round.big_blind
    @round.small_blind = @round.big_blind / 2
    players = Player.all

    players.each do |player|
      player.pass = false
      player.is_playing = true
      player.winner = false
      player.allin = 0
      player.save
    end


    respond_to do |format|
      if @round.save
        session[:round_id] = @round.id
        format.html { redirect_to root_url, notice: 'Round was successfully created.' }
        format.json { render action: 'show', status: :created, location: @round }
      else
        format.html { render action: 'new' }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to rounds_url, notice: 'Round was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url }
      format.json { head :no_content }
    end

    session[:round_id] = nil
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:pot, :big_blind, :small_blind, :call_value)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_for @round, :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :big_blind, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :big_blind, :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rounds_path, :class => 'btn' %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<%- model_class = Round -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rounds/index.html.erb
<%- model_class = Round -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pot) %></th>
      <th><%= model_class.human_attribute_name(:big_blind) %></th>
      <th><%= model_class.human_attribute_name(:small_blind) %></th>
      <th><%= model_class.human_attribute_name(:call_value) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= link_to round.id, round_path(round) %></td>
        <td><%= round.pot %></td>
        <td><%= round.big_blind %></td>
        <td><%= round.small_blind %></td>
        <td><%= round.call_value %></td>
        <td><%= round.level %></td>
        <td><%=l round.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_round_path(round), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      round_path(round),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_round_path,
            :class => 'btn btn-primary' %>

app/views/rounds/new.html.erb
<%- model_class = Round -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rounds/show.html.erb
<%- model_class = Round -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pot) %>:</strong></dt>
  <dd><%= @round.pot %></dd>
  <dt><strong><%= model_class.human_attribute_name(:big_blind) %>:</strong></dt>
  <dd><%= @round.big_blind %></dd>
  <dt><strong><%= model_class.human_attribute_name(:small_blind) %>:</strong></dt>
  <dd><%= @round.small_blind %></dd>
  <dt><strong><%= model_class.human_attribute_name(:call_value) %>:</strong></dt>
  <dd><%= @round.call_value %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              rounds_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_round_path(@round), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              round_path(@round),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>