config/routes.rb
Poker::Application.routes.draw do
  resources :line_items

  get "game/index"
  resources :rounds

  resources :players

  get '/players/toggleplay/:id' => 'players#toggleplay',:as => 'toggle_player'

  root :to => "game#index"

  

end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :line_items
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_url, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to players_url, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  def toggleplay
    @player = Player.find(params[:id])
    if @player.is_playing == true
      @player.is_playing = false
    else
      @player.is_playing = true
    end
    @player.save
    
    redirect_to players_url  

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :balance, :imageurl)
    end
end

app/helpers/players_helper.rb
module PlayersHelper

	# def check_toggle(plr)

	# 	return <%= link_to "Toggle", toggle_player_path(plr.id), :class => 'btn btn-success btn-small'  %>

	# 	# if session[:round_id] != nil
	# 	# 	return link_to "Delete Round", round_path(session[:round_id]), :method => :delete,  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn'
	# 	# else
	# 	# 	return link_to "Create Round", new_round_path, :class => 'btn btn-success btn-large'
	# 	# end	

	# end


	def check_toggle(plr)

		if plr.is_playing == true
			return link_to "Yes", toggle_player_path(plr.id), :class => 'btn btn-success btn-small togbut' 
		else
			return link_to "No", toggle_player_path(plr.id), :class => 'btn btn-danger btn-small togbut'
		end
	end


	def round_estimate(plr, rnd)

		total = LineItem.where(:player_id => plr.id, :round_id => rnd.id).sum(&:amount)

		return total
	end

	def get_call_val(plr, rnd)

		total_level = LineItem.where(:player_id => plr.id, :round_id => rnd.id, :level => rnd.level).sum(&:amount)

		return rnd.call_value - total_level 
	end


end

app/views/players/_form.html.erb
<%= form_for @player, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :balance, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :balance, :class => 'text_field' %>
    </div>
  </div>

    <div class="control-group">
    <%= f.label :imageurl, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :imageurl, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                players_path, :class => 'btn' %>
  </div>
<% end %>

app/views/players/_player.html.erb
<% if player.pass == true && player.is_playing == true  %>
	<li class="span3 passed">
<% end %>

<% if player.is_playing == false %>
	<li class="span3 folded">
<% end %>

<% if player.pass == false && player.is_playing == true && player.winner == false %>	
	
	<li class="span3">
	
<% end %>

<% if player.pass == false && player.is_playing == true && player.winner == true %>	
	
	<li class="span3 winner">
	
<% end %>



<% @curr = current_round %>
	<div class="thumbnail" style="text-align:center">

	  <img data-src="holder.js/300x200" alt="300x200" style="width: 160px; height: 180px; margin-top:10px" src=
	  <%=  "https://graph.facebook.com/" + player.imageurl + "/picture?width=160&height=180" %>

	  >

	  <div class="caption">
	    <h3> <%= player.name %> </h3>
	    <p><h4>Bal : <%= number_to_currency(player.balance, :unit => "₹")   %></h4></p>
	    <p><h4>Thrown : <%=  number_to_currency(round_estimate(player, current_round), :unit => "₹") %></h4></p><hr>
	    <p>				     
	    
	    <% if @curr.level < 5 %>

	     <%= form_tag(line_items_path(:fold => 1, :player_id => player), method: "post") do %>

			  <%= submit_tag("Fold", :class => 'btn-info btn') %>
			<% end %>

				     <%= form_tag(line_items_path(:allin => 1, :player_id => player, :round_id => current_round, :level => @curr.level, :pass => true), method: "post") do %>

			  <%= submit_tag("All In", :class => 'btn-warning btn') %>
			<% end %>

	 

		
	      
	      <%= button_to "Call : ₹ #{get_call_val(player, @curr)}", line_items_path(:player_id => player, :round_id => current_round, :level => @curr.level, :amount => get_call_val(player, @curr), :pass => true) , :class => 'btn btn-success' %> 

	   <!--    <div style="" class="raise_btn"><a href="#" class="btn-danger btn">Raise</a> <input style="width:50px"></div> -->

		    <%= form_tag(line_items_path(:player_id => player, :round_id => current_round, :level => @curr.level, :pass => true), method: "post") do %>

			  <%= text_field_tag :raise %>

			  <%= submit_tag("Raise", :class => 'btn btn-danger') %>
			<% end %>

			<% else %>

			<%= form_tag(line_items_path(:winner => 1, :player_id => player), method: "post") do %>

			  <%= submit_tag("Winner", :class => 'btn-success btn-large winner') %>
			<% end %>

			<% end %>
	    </p>
	  </div>

	</div>

</li>

app/views/players/edit.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/index.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:balance) %></th>
      <th>Playing ?</th>
      <th>Passed ?</th>
      <th>Winner ?</th>
      <!-- <th><%= model_class.human_attribute_name(:created_at) %></th> -->
      <th><%= model_class.human_attribute_name(:imageurl) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.id, player_path(player) %></td>
        <td><%= player.name %></td>
        <td><%= player.balance %></td>
        <td>
        <%=  check_toggle(player) %>
        </td>
        <td><%= player.pass %></td>
        <td><%= player.winner %></td>
        <!-- <td><%=l player.created_at %></td> -->
        <td><%= player.imageurl %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_player_path(player), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      player_path(player),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_player_path,
            :class => 'btn btn-primary' %>

app/views/players/new.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/show.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @player.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:balance) %>:</strong></dt>
  <dd><%= @player.balance %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              players_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_player_path(@player), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              player_path(@player),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/players/toggleplay.js.erb
$('#tog_td').html('<%=j check_toggle(@player)%>');