config/routes.rb
Poker::Application.routes.draw do
  resources :line_items

  get "game/index"
  resources :rounds

  resources :players

  get '/players/toggleplay/:id' => 'players#toggleplay',:as => 'toggle_player'

  root :to => "game#index"

  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

	belongs_to :player
	belongs_to :round

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
#  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
  #  @line_item = LineItem.ne₹w(params[])

  #  render :text => params[:player_id]
    #@line_item = nil


  if params[:result]

    rnd = Round.find(session[:round_id])  

    pls = Player.where(:winner => true, :is_playing => true)

    summ = rnd.pot / pls.count
    #summ = summ.round_down(2)
    rnd.pot = 0

    pls.each do |pl|

      pl.balance = pl.balance + summ

      pl.save

      @line_item = LineItem.new(:player_id => pl.id, :round_id => rnd.id , :amount => 0 - summ,  :level => rnd.level, :pass => false )
      @line_item.save

    end
    rnd.save
    redirect_to root_url
    return

  end

  if params[:winner]

      pl = Player.find(params[:player_id])
      if pl.winner == false
        pl.winner = true
      else
        pl.winner = false
      end
      pl.save

      redirect_to root_url
      return

    end

   if params[:check]

      if Player.where(:is_playing => true, :pass => true).count == 0

        rnd = Round.find(session[:round_id])  
        rnd.level = rnd.level + 1

        players = Player.where(:is_playing => true)

        players.each do |player|
          player.pass = false
          player.save
        end

        rnd.call_value = rnd.big_blind
         rnd.save
     end
     redirect_to root_url
     return
   end


   
    if params[:fold]
      pl = Player.find(params[:player_id])
      pl.is_playing = false
      pl.save

      if Player.where(:is_playing => true, :pass => false).count == 0

      rnd = Round.find(session[:round_id])  
      rnd.level = rnd.level + 1

      players = Player.where(:is_playing => true)

      players.each do |player|
        player.pass = false
        player.save
      end

      rnd.call_value = rnd.big_blind
       rnd.save
    end

      redirect_to root_url
      return

    end

    if params[:raise]

      params[:amount] = params[:raise].to_d - LineItem.where(:player_id => params[:player_id], :round_id => params[:round_id], :level => params[:level]).sum(&:amount)
    end


    if params[:allin]
       pl = Player.find(params[:player_id])
      params[:amount] =  pl.balance #- LineItem.where(:player_id => params[:player_id], :round_id => params[:round_id], :level => params[:level]).sum(&:amount)
       rnd = Round.find(session[:round_id])  
       if rnd.call_value < pl.balance
        params[:raise] = pl.balance
       end

       pl.is_playing = false
       pl.allin = rnd.level
       pl.save

    end

    @line_item = LineItem.new(:player_id => params[:player_id], :round_id => params[:round_id], :amount => params[:amount],  :level => params[:level], :pass => params[:pass] )
    
    if  @line_item.player.balance < params[:amount].to_d
      redirect_to root_url
      return
    end

    if params[:raise]

      if params[:raise].to_d < @line_item.round.call_value
        redirect_to root_url
        return
      end

       @line_item.round.call_value = params[:raise]

      players = Player.where(:is_playing => true)

      players.each do |player|
        player.pass = false
        if(player.id != params[:player_id])
        player.save
      end
      end

    end

    

    @line_item.round.pot = @line_item.round.pot + params[:amount].to_d
    

    @line_item.player.pass = params[:pass]
    @line_item.player.balance = @line_item.player.balance - params[:amount].to_d

    @line_item.save
    @line_item.player.save

    if Player.where(:is_playing => true, :pass => false).count == 0

      @line_item.round.level = @line_item.round.level + 1
      players = Player.where(:is_playing => true)

      players.each do |player|
        player.pass = false
        player.save
      end

      @line_item.round.call_value = @line_item.round.big_blind

    end

    @line_item.round.save
    redirect_to root_url

    # respond_to do |format|
    #   if @line_item.save
    #     format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
    #     format.json { render action: 'show', status: :created, location: @line_item }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @line_item.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
     # params.require(:line_item).permit(:player_id, :round_id, :level, :amount, :pass)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for @line_item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :player_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :player_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :round_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :round_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :level, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :level, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :pass, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pass, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                line_items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/line_items/index.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:player_id) %></th>
      <th><%= model_class.human_attribute_name(:round_id) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:pass) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= link_to line_item.id, line_item_path(line_item) %></td>
        <td><%= line_item.player_id %></td>
        <td><%= line_item.round_id %></td>
        <td><%= line_item.level %></td>
        <td><%= line_item.amount %></td>
        <td><%= line_item.pass %></td>
        <td><%=l line_item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_line_item_path(line_item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      line_item_path(line_item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_line_item_path,
            :class => 'btn btn-primary' %>

app/views/line_items/new.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/line_items/show.html.erb
<%- model_class = LineItem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:player_id) %>:</strong></dt>
  <dd><%= @line_item.player_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:round_id) %>:</strong></dt>
  <dd><%= @line_item.round_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:level) %>:</strong></dt>
  <dd><%= @line_item.level %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @line_item.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pass) %>:</strong></dt>
  <dd><%= @line_item.pass %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              line_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_line_item_path(@line_item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              line_item_path(@line_item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>