config/routes.rb
Poker::Application.routes.draw do
  resources :line_items

  get "game/index"
  resources :rounds

  resources :players

  get '/players/toggleplay/:id' => 'players#toggleplay',:as => 'toggle_player'

  root :to => "game#index"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title><%= content_for?(:title) ? yield(:title) : "Poker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag params[:controller] %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

   
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/game/index">Poker</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Players", players_url  %></li>
              <li><%= link_to "Rounds", rounds_url  %></li>
              <li><%= link_to "Game", '/game/index'  %></li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" id="main_cont">
        <div class="row">
          
          <div class="span3 ">
            <div class="well sidebar-nav affix" style="text-align:center;">
             <%= check_session_btn  %>
             <% if session[:round_id] != nil %>

             <% @curr_round = current_round %>
              <hr>
              <h3>Pot : ₹ <%= @curr_round.pot %></h3>
              <h4>Call : ₹ <%= @curr_round.call_value %></h4>
              <h4>Level : <%= @curr_round.level %></h4>
                <%= form_tag(line_items_path(:check => 1), method: "post") do %>

        <%= submit_tag("Check", :class => 'btn-primary btn') %>
      <% end %>

      <% if @curr_round.level == 5 %>
         <%= form_tag(line_items_path(:result => 1), method: "post") do %>

        <%= submit_tag("Result", :class => 'btn-primary btn') %>
      <% end %>

      <% end %>

             <% end %>

            </div><!--/.well -->
          </div><!--/span-->
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

<!--       <footer>
        <p>&copy; Company 2013</p>
      </footer> -->

    </div> <!-- /container -->

  </body>

 <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] %>
  <script type="text/javascript">

$('.passed').find('a').attr('disabled', 'true');
$('.passed').find('input').attr('disabled', 'true');
$('.folded').find('a').attr('disabled', 'true');
$('.folded').find('input').attr('disabled', 'true');
$('.folded .winner').css('visibility', 'hidden');

</script>    
</html>